
services:
  api:
    command: npx nodemon server.js
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://asemb_user:asemb_password_2025@postgres:5432/asemb
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - POSTGRES_USER=asemb_user
      - POSTGRES_PASSWORD=asemb_password_2025
      - POSTGRES_DB=asemb
    volumes:
      - ./api:/app
      - /app/node_modules

