module.exports = {
  apps: [
    {
      name: 'bookie-backend',
      script: 'dist/server.js',
      cwd: '/var/www/bookie/backend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        BACKEND_PORT: 8085,
        POSTGRES_HOST: '91.99.229.96',
        POSTGRES_PORT: '5432',
        POSTGRES_DB: 'bookie_lsemb',
        POSTGRES_USER: 'postgres',
        POSTGRES_PASSWORD: 'Semsiye!22',
        REDIS_HOST: 'localhost',
        REDIS_PORT: '6379',
        REDIS_PASSWORD: 'Semsiye!22',
        REDIS_DB: '4',
      },
      error_file: '/var/www/bookie/logs/backend-error.log',
      out_file: '/var/www/bookie/logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: 'bookie-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/var/www/bookie/frontend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      error_file: '/var/www/bookie/logs/frontend-error.log',
      out_file: '/var/www/bookie/logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'bookie-python',
      script: 'main.py',
      cwd: '/var/www/bookie/backend/python-services',
      interpreter: 'python3',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PORT: 8003,
      },
      error_file: '/var/www/bookie/logs/python-error.log',
      out_file: '/var/www/bookie/logs/python-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
  ],
};
