module.exports = {
  apps: [
    {
      name: 'emlakai-backend',
      script: 'dist/server.js',
      cwd: '/var/www/emlakai/backend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        BACKEND_PORT: 8084,
        POSTGRES_HOST: '91.99.229.96',
        POSTGRES_PORT: '5432',
        POSTGRES_DB: 'emlakai_lsemb',
        POSTGRES_USER: 'postgres',
        POSTGRES_PASSWORD: 'Semsiye!22',
        REDIS_HOST: 'localhost',
        REDIS_PORT: '6379',
        REDIS_PASSWORD: 'Semsiye!22',
        REDIS_DB: '3',
      },
      error_file: '/var/www/emlakai/logs/backend-error.log',
      out_file: '/var/www/emlakai/logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
    },
    {
      name: 'emlakai-frontend',
      script: 'npm',
      args: 'start',
      cwd: '/var/www/emlakai/frontend',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      error_file: '/var/www/emlakai/logs/frontend-error.log',
      out_file: '/var/www/emlakai/logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
    {
      name: 'emlakai-python',
      script: 'main.py',
      cwd: '/var/www/emlakai/backend/python-services',
      interpreter: 'python3',
      instances: 1,
      exec_mode: 'fork',
      env: {
        PORT: 8002,
      },
      error_file: '/var/www/emlakai/logs/python-error.log',
      out_file: '/var/www/emlakai/logs/python-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
    },
  ],
};
