#!/bin/bash
echo "🔧 Production'u düzeltmek için:"
echo ""
echo "1. Redis auth şifresi kontrol et:"
echo "   - /var/www/lsemb/.env dosyasını kontrol et"
echo ""
echo "2. Backend'i yeniden başlat:"
echo "   cd /var/www/lsemb"
echo "   pm2 restart lsemb-backend"
echo ""
echo "3. PostgreSQL query hatalarını düzelt:"
echo "   - rag-chat.service.ts:1860 satırında SQL sorgusu hatalı"
echo "   - SELECT DISTINCT ile ORDER BY uyumsuzluğu"
echo ""
echo "4. Logları takip et:"
echo "   pm2 logs lsemb-backend --lines 50 --nostream"
