# renew_before_expiry = 30 days
version = 4.2.0
archive_dir = /etc/letsencrypt/archive/luwi.dev
cert = /etc/letsencrypt/live/luwi.dev/cert.pem
privkey = /etc/letsencrypt/live/luwi.dev/privkey.pem
chain = /etc/letsencrypt/live/luwi.dev/chain.pem
fullchain = /etc/letsencrypt/live/luwi.dev/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 5cd8fff251041c33c0d86191b50f50c2
authenticator = nginx
installer = nginx
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
